### ISSUE TITLE
Minor versions does not make any effect

### ISSUE THREAD

**Issue by shyim** [VKCOM/php-parser#32]
I want to lint PHP files, if they are syntax okay for a specific PHP version. It does work well for major versions, but not minor like 7.2, 7.4, 8.1

## PHP Version

7.2

## Code Example

Code with Typed Property

## Actual Behavior

It parses the file and does not complain.

## Expected Behavior

Expect an error from the parser, as typed properties is available since 7.4

**Comment by i582** [comment]
Hi
Unfortunately, this does not make sense in the current parser, since such granularity is not needed. 

If you want to check for syntax constructs that are not in a certain standard, then it makes sense to use a major version of PHP for parsing and then in an additional traversal of the tree to check if this or that syntactic construct exists.

**Comment by shyim** [comment]
Hey,

Yea I can fully understand why it's not implemented. I guess I will compile some php versions staticly and throw then into an AWS lambda. and the lambda should check if the syntax is ok for a given version
